apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://ai-loki:3100
    isDefault: false
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: '"request_id":"([^"]+)"'
          name: RequestID
          url: '${__value.raw}'
